spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  data:
    jdbc:
      repositories:
        enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource: DEBUG
